### ISSUE TITLE
'xxxx': [Object] is displayed after sorting?

### ISSUE THREAD

**Issue by strus38** [IndigoUnited/js-deep-sort-object#6]
Hi
Trying a very simple example like this:
```
$ node test.js > o2
$ cat o2
{ _meta: 
   { hostvars: 
      { '172.31.42.128': [Object],
...
```
with this in output2.json:

```
$ cat output2.json 
{
  "_meta": {
    "hostvars": {
      "172.31.42.128": {
        "ec2__in_monitoring_element": false, 
        "ec2_ami_launch_index": "0", 
        "ec2_architecture": "x86_64", 
        "ec2_client_token": "", 
....
```

The output2.json file is the result of the ec2.py script used by Ansible.

What is wrong in what I am doing?
Thanks

**Comment by satazor** [comment]
You are not calling sort object.. try

```js
configs = sortobject(configs)

**Comment by strus38** [comment]
yep, in between I updated the code, but this is JSON.parse which is doing that. Need to see why.
You can close. Sorry.
